---
- hosts: all
  become: true
  tasks:
    - name: update and upgrade repository
      apt:
        update_cache: yes
        upgrade: dist
    - name: install apache2
      apt:
        name: apache2
        state: latest
